
	<option>Americano</option>
	<option>Alemão</option>
	<option>Árabe</option>
	<option>Afegão</option>
	<option>Argentino</option>
	<option>Australiano</option>
	<option>Austríaco</option>
	<option>Bangladês</option>
	<option>Britânico</option>
	<option>Bielorrusso</option>
	<option>Belga</option>
	<option>Boliviano</option>
	<option>Brasileiro</option>
	<option>Canadense</option>
	<option>Costa-marfinense</option>
	<option>Chinês</option>
	<option>Croata</option>
	<option>Cubano</option>
	<option>Dinamarquês</option>
	<option>Eslovaco</option>
	<option>Espanhol</option>
	<option>Equatoriano</option>
	<option>Egípcio</option>
	<option>Finlandês</option>
	<option>Francês</option>
	<option>Filipino</option>
	<option>Grego</option>
	<option>Húngaro</option>
	<option>Holandês</option>
	<option>Inglês</option>
	<option>Iraniano</option>
	<option>Irlandês</option>
	<option>Israelita</option>
	<option>Italiano</option>
	<option>Japonês</option>
	<option>Libanês</option>
	<option>Luxemburguês</option>
	<option>Malaio</option>
	<option>Mexicano</option>
	<option>Marroquino</option>
	<option>Neozelandês</option>
	<option>Norueguês</option>
	<option>Panamenho</option>
	<option>Paraguaio</option>
	<option>Peruano</option>
	<option>Polonês</option>
	<option>Queniano</option>
	<option>Russo</option>
	<option>Sueco</option>
	<option>Suiço</option>
