"""empty message

Revision ID: 169c619d8ffb
Revises: 36dcc6f71dbb
Create Date: 2020-01-14 02:01:38.771328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169c619d8ffb'
down_revision = '36dcc6f71dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('serie', sa.String(length=20), nullable=True))
    op.add_column('alunos', sa.Column('turma', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alunos', 'turma')
    op.drop_column('alunos', 'serie')
    # ### end Alembic commands ###
