"""empty message

Revision ID: 36dcc6f71dbb
Revises: 
Create Date: 2020-01-10 18:10:34.878437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dcc6f71dbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=True),
    sa.Column('nascimento', sa.String(length=50), nullable=True),
    sa.Column('est_civil', sa.String(length=10), nullable=True),
    sa.Column('sexo', sa.String(length=10), nullable=True),
    sa.Column('nacionalidade', sa.String(length=50), nullable=True),
    sa.Column('nome_responsavel', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=250), nullable=True),
    sa.Column('bairro', sa.String(length=250), nullable=True),
    sa.Column('cidade', sa.String(length=250), nullable=True),
    sa.Column('cep', sa.String(length=50), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primeira_nota', sa.String(length=10), nullable=True),
    sa.Column('segunda_nota', sa.String(length=10), nullable=True),
    sa.Column('terceira_nota', sa.String(length=10), nullable=True),
    sa.Column('media_final', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_table('alunos')
    # ### end Alembic commands ###
